import os
import asyncio
from datetime import datetime, timedelta
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from google.cloud import firestore
from google import genai 
from mcp.server.fastmcp import FastMCP
from google.oauth2 import service_account
from googleapiclient.discovery import build

# 1. Initialization
app = FastAPI(title="Interview Orchestrator")
mcp = FastMCP("Interview-Assistant")

# GCP Configuration
PROJECT_ID = os.getenv("GCP_PROJECT_ID", "interview-orchestrator")
LOCATION = os.getenv("GCP_LOCATION", "us-central1")
CALENDAR_ID = os.getenv("CALENDAR_ID")

client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)
db = firestore.Client(project=PROJECT_ID)

class InterviewRequest(BaseModel):
    company_name: str
    target_role: str
    interview_date: str



def get_calendar_service():
    SCOPES = ['https://www.googleapis.com/auth/calendar']
    
    # Check if running on local/cloud shell with file or on Cloud Run with IAM
    if os.path.exists('service-account.json'):
        creds = service_account.Credentials.from_service_account_file(
            'service-account.json', scopes=SCOPES)
    else:
        import google.auth
        creds, _ = google.auth.default(scopes=SCOPES)
        
    return build('calendar', 'v3', credentials=creds)

# MCP Tool Definition
@mcp.tool()
async def schedule_prep_alert(company: str, date_str: str):
    """
    Calculates the best time for a prep session 1 day before the interview.
    """
    try:
        # 1. Logic: Set Prep for 6:00 PM the day before
        interview_dt = datetime.strptime(date_str, "%Y-%m-%d")
        prep_dt = interview_dt - timedelta(days=1)
        prep_start = prep_dt.replace(hour=18, minute=0).isoformat()
        prep_end = prep_dt.replace(hour=20, minute=0).isoformat()
        
        service = get_calendar_service()
        
        # Falls back to 'primary' if no environment variable is set
        cal_id = CALENDAR_ID or 'primary'

        event = {
            'summary': f'Interview Prep: {company}',
            'description': f'Automated prep session generated by Interview Orchestrator.',
            'start': {'dateTime': prep_start, 'timeZone': 'Asia/Kolkata'},
            'end': {'dateTime': prep_end, 'timeZone': 'Asia/Kolkata'},
        }

        event_result = service.events().insert(calendarId=cal_id, body=event).execute()
        return f"SUCCESS: Event created! View here: {event_result.get('htmlLink')}"

    except Exception as e:
        return f"Calendar Error: {str(e)}"

# 3. Sub-Agent Logic 
async def run_sub_agent(agent_name: str, task: str, company: str):
    """Executes a specialized agent task with token limits"""
    prompt = f"You are the {agent_name}. Research the following for {company}: {task}. Provide 3 short key insights.No intro, no outro."
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "max_output_tokens": 1000, # Objective : Keep usage minimum
            "temperature": 0.2        
        }
    )
    return {agent_name: response.text}

# 4. Main Orchestrator Endpoint
@app.post("/research")
async def start_research(request: InterviewRequest):
    try:
        # Step A: Initialize Firestore Document
        doc_ref = db.collection("interviews").document()
        
        # Step B: Phase 1 - High Level Plan (Cost Optimized)
        plan_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"Provide a 3-bullet research plan for {request.company_name} - {request.target_role}.",
            config={"max_output_tokens": 1000}
        )
        research_plan = plan_response.text

        # Step C: Phase 2 - Parallel execution (Agents + MCP Tool)
        agent_tasks = [
            run_sub_agent("Market_Agent", "Market position and top 2 competitors", request.company_name),
            run_sub_agent("Tech_Agent", "Core technology stack and recent product launches", request.company_name),
            run_sub_agent("Culture_Agent", "Company values and common interview themes", request.company_name)
        ]
        
        # Trigger the MCP tool call
        mcp_task = schedule_prep_alert(request.company_name, request.interview_date)
        
        # Run everything at once for efficiency
        results, mcp_msg = await asyncio.gather(asyncio.gather(*agent_tasks), mcp_task)
        
        # Combine insights
        combined_insights = {}
        for r in results:
            combined_insights.update(r)

        # Step D: Save state to Firestore
        state_data = {
            "company_name": request.company_name,
            "role": request.target_role,
            "status": "Complete",
            "primary_plan": research_plan,
            "detailed_analysis": combined_insights,
            "mcp_action_log": mcp_msg,
            "created_at": firestore.SERVER_TIMESTAMP
        }
        doc_ref.set(state_data)
        
        return {
            "status": "Success", 
            "document_id": doc_ref.id, 
            "mcp_log": mcp_msg,
            "insights": combined_insights
        }
        
    except Exception as e:
        print(f"Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# Step E: Endpoint to expose MCP status
@app.get("/mcp")
async def get_mcp_info():
    return {"mcp_status": "active", "tools_integrated": ["schedule_prep_alert"]}