import os
import asyncio
from datetime import datetime, timedelta
from googleapiclient.discovery import build
from google.oauth2 import service_account

CALENDAR_ID = os.getenv("CALENDAR_ID", "anant07singh2004@gmail.com")

def get_calendar_service():
    SCOPES = ['https://www.googleapis.com/auth/calendar']
    
    # Logic for Service Account (Local) vs Application Default Credentials (Cloud Run)
    if os.path.exists('service-account.json'):
        creds = service_account.Credentials.from_service_account_file(
            'service-account.json', scopes=SCOPES)
    else:
        import google.auth
        creds, _ = google.auth.default(scopes=SCOPES)
        
    return build('calendar', 'v3', credentials=creds)

async def schedule_prep_alert(company: str, date_str: str):
    """
    Calculates the best time for a prep session 1 day before the interview.
    """
    try:
        # 1. Logic: Set Prep for 6:00 PM the day before
        interview_dt = datetime.strptime(date_str, "%Y-%m-%d")
        prep_dt = interview_dt - timedelta(days=1)
        prep_start = prep_dt.replace(hour=18, minute=0).isoformat()
        prep_end = prep_dt.replace(hour=20, minute=0).isoformat()
        
        service = get_calendar_service()
        
        # Falls back to 'primary' if no environment variable is set
        cal_id = CALENDAR_ID or 'primary'

        event = {
            'summary': f'Interview Prep: {company}',
            'description': f'Automated prep session generated by Interview Orchestrator.',
            'start': {'dateTime': prep_start, 'timeZone': 'Asia/Kolkata'},
            'end': {'dateTime': prep_end, 'timeZone': 'Asia/Kolkata'},
        }

        event_result = service.events().insert(calendarId=cal_id, body=event).execute()
        return f"SUCCESS: Event created! View here: {event_result.get('htmlLink')}"

    except Exception as e:
        return f"Calendar Error: {str(e)}"